openapi: 3.0.0

info:
  title: "YellowCab API"
  description: "The YellowCab API provides relevant and authentic statistics about New York Yellow Trips. To access these, it is necessary to carry out an authentication and authorization process."
  version: "1.0"
  termsOfService: "https://yellowcab.com/terms"
  contact:
    name: "YellowCab API"
    url: "https://yellowcab.com/api"
    email: "computacaonuvem2022@gmail.com"
  license:
    name: ""
    url: "https://yellowcab.com/price"

servers:
  - url: "/api"

tags:
  - name: Statistics
    description: "Statistics Results of New York Yellow Cab Ride Information"

paths:
  /stats/time:
    get:
      operationId: "statistics.get_time_stats"
      tags:
        - Statistics
      summary: Get time statistics in two rides
      description: Returns time statistics of two rides.
      parameters:
        - $ref: "#/components/parameters/PULocationName"
        - $ref: "#/components/parameters/DOLocationName"
        - $ref: "#/components/parameters/PULocationName2"
        - $ref: "#/components/parameters/DOLocationName2"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeStatistics"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                title: Invalid Names supplied
                type: string
                example: Invalid Names supplied
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                title: Route time statistics not found
                type: string
                example: Route time statistics not found

  /stats/congestion:
    get:
      operationId: "statistics.get_congestion_stats"
      tags:
        - Statistics
      summary: Get congestion statistics
      description: Returns congestion statistics per ride.
      parameters:
        - $ref: "#/components/parameters/PULocationName"
        - $ref: "#/components/parameters/DOLocationName"
        - $ref: "#/components/parameters/PULocationName2"
        - $ref: "#/components/parameters/DOLocationName2"
        - $ref: "#/components/parameters/token"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CongestionStatistics"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                title: Invalid Names supplied
                type: string
                example: Invalid Names supplied
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                title: Congestion statistics not found
                type: string
                example: Congestion statistics not found

  /stats/cabs:
    get:
      operationId: "statistics.get_cab_stats"
      tags:
        - Statistics
      summary: Get cab statistics
      description: Returns the number of cabs with the LocationName as destination or source.
      parameters:
        - $ref: "#/components/parameters/LocationName"
        - $ref: "#/components/parameters/LocationName2"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CabStatistics"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                title: Invalid LocationName supplied
                type: string
                example: Invalid LocationName supplied
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                title: Cabs statistics not found
                type: string
                example: Cabs statistics not found

  /stats/health:
    get:
      operationId: "statistics.health"
      tags:
        - Statistics
      summary: Check microservice health
      responses:
        "200":
          description: Successful response
        "404":
          description: Not found response

components:
  parameters:
    PULocationName:
      name: PULocationName
      in: query
      description: "PULocationName. Example: Central Park. TLC Taxi Zone in which the taximeter was engaged."
      required: True
      schema:
        type: string
        example: "Central Park"
    DOLocationName:
      name: DOLocationName
      in: query
      description: "DOLocationName. Example: JFK Airport. TLC Taxi Zone in which the taximeter was disengaged."
      required: True
      schema:
        type: string
        example: "Central Park"
    PULocationName2:
      name: PULocationName2
      in: query
      description: "PULocationName 2. Example: Central Park. TLC Taxi Zone in which the taximeter was engaged."
      required: True
      schema:
        type: string
        example: "Central Park"
    DOLocationName2:
      name: DOLocationName2
      in: query
      description: "DOLocationName 2. Example: Newark Airport. TLC Taxi Zone in which the taximeter was disengaged."
      required: True
      schema:
        type: string
        example: "Newark Airport"
    LocationName:
      name: LocationName
      description: "Location Name 1. Example: Central Park. TLC Taxi Zone"
      in: query
      required: True
      schema:
        type: "string"
    LocationName2:
      name: LocationName2
      description: "Location Name 2. Example: Bronx Park. TLC Taxi Zone"
      in: query
      required: True
      schema:
        type: "string"
    token:
      name: token
      in: query
      description: "Access token"
      required: True
      schema:
        type: string
        example: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYteWVsbG93LWNhYi51ay5hdXRoMC5jb20vIn0..rvSTar6JtInHF7Zt.MjgQujk5ogDaBeYXwUUESUTbk5EocFNWl8EZKadD1RSc368-mRTYNwPeDFzclATm9RcNQMh5rn6MeeRQYQAIYmcvM-wUJpV72_JGc9iX7w2a9_y6mpmcEMpUxxvYP67a7A3EEK3zQyF07szvHjDSYXXuygHOR16924YlFfGub8ErzYXQIPygQzobF-Hra0gV_SuAxSBaKho9CuTwAVv5Ih5qKfr4dvzPXnyggM4nPybi8TFy1SkZeNCmb6c2hMMGzR0Qoakc08bCWPKkLgTeTPJgUZqXziHHwStHE-TIJi3FhVR33Bu8gMQdUzV-WLP8Zoz_l0_F.MUccfem5-LBPkYI1WIQm1A"

  schemas:
    TimeStatistics:
      type: object
      properties:
        trip1:
          type: object
          description: First Trip
          properties:
            min_time:
              type: number
              description: Minimum time in minutes
            max_time:
              type: number
              description: Maximum time in minutes
            avg_time:
              type: number
              description: Average time in minutes
        trip2:
          type: object
          description: Second Trip
          properties:
            min_time:
              type: number
              description: Minimum time in minutes
            max_time:
              type: number
              description: Maximum time in minutes
            avg_time:
              type: number
              description: Average time in minutes

    CongestionStatistics:
      type: object
      properties:
        trip1:
          type: object
          description: First Trip
          properties:
            min_congestion:
              type: number
              description: Minimum congestion surcharge
            max_congestion:
              type: number
              description: Maximum congestion surcharge
            avg_congestion:
              type: number
              description: Average congestion surcharge
        trip2:
          type: object
          description: Second Trip
          properties:
            min_congestion:
              type: number
              description: Minimum congestion surcharge
            max_congestion:
              type: number
              description: Maximum congestion surcharge
            avg_congestion:
              type: number
              description: Average congestion surcharge

    CabStatistics:
      type: object
      properties:
        number_cabs_first_location:
          type: number
          description: Number of cabs at first location
        number_cabs_second_location:
          type: number
          description: Number of cabs at second location
