apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yellow-cab-zones-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yellow-cab-zones-d
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yellow-cab-authentication-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yellow-cab-authentication-d
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yellow-cab-business-intelligence-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yellow-cab-business-intelligence-d
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yellow-cab-statistics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yellow-cab-statistics-d
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
