# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zone.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nzone.proto\x12\x06zonepb\"!\n\x0bZoneRequest\x12\x12\n\nlocationID\x18\x01 \x01(\x03\"*\n\x0cZoneResponse\x12\x1a\n\x04zone\x18\x01 \x01(\x0b\x32\x0c.zonepb.Zone\"\x1c\n\x0cZonesRequest\x12\x0c\n\x04zone\x18\x01 \x03(\t\",\n\rZonesResponse\x12\x1b\n\x05zones\x18\x01 \x03(\x0b\x32\x0c.zonepb.Zone\"O\n\x04Zone\x12\x12\n\nlocationID\x18\x01 \x01(\x03\x12\x0f\n\x07\x62orough\x18\x02 \x01(\t\x12\x14\n\x0cservice_zone\x18\x03 \x01(\t\x12\x0c\n\x04zone\x18\x04 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xca\x01\n\x0bZoneService\x12\x36\n\x07GetZone\x12\x13.zonepb.ZoneRequest\x1a\x14.zonepb.ZoneResponse\"\x00\x12\x39\n\x08GetZones\x12\x14.zonepb.ZonesRequest\x1a\x15.zonepb.ZonesResponse\"\x00\x12H\n\x0bHealthCheck\x12\x1a.zonepb.HealthCheckRequest\x1a\x1b.zonepb.HealthCheckResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zone_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ZONEREQUEST._serialized_start = 22
    _ZONEREQUEST._serialized_end = 55
    _ZONERESPONSE._serialized_start = 57
    _ZONERESPONSE._serialized_end = 99
    _ZONESREQUEST._serialized_start = 101
    _ZONESREQUEST._serialized_end = 129
    _ZONESRESPONSE._serialized_start = 131
    _ZONESRESPONSE._serialized_end = 175
    _ZONE._serialized_start = 177
    _ZONE._serialized_end = 256
    _HEALTHCHECKREQUEST._serialized_start = 258
    _HEALTHCHECKREQUEST._serialized_end = 278
    _HEALTHCHECKRESPONSE._serialized_start = 280
    _HEALTHCHECKRESPONSE._serialized_end = 317
    _ZONESERVICE._serialized_start = 320
    _ZONESERVICE._serialized_end = 522
# @@protoc_insertion_point(module_scope)
